version: '3'

networks:
  app-tier:
    driver: bridge

services:
  todo-api:
    container_name: todo-api
    build: .
    networks:
      - app-tier
    ports:
      - "3000:3000"
    depends_on:
      - dbpgsql
    volumes:
      - ".:/todo-api/src/"

  dbpgsql:
    container_name: dbpgsql
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - app-tier